feat(util): add themeResolver
yext/visual-editor pull request #69
Opened 2024-10-02 17:25 UTC by briantstephan

This adds a themeResolver util that converts a ThemeConfig to a TailwindConfig format, and combines it with the developer-specified tailwind config that is also passed in. Configurations made by the developer take priority over the user/marketer's theme config. Tested by building locally and using the local build in the starter. I part of the tailwind config into theme.config.ts and passed both the theme config and the rest of the tailwind config into themeResolver, which provided the same output as the old tailwind config.

2024-10-02 17:49 UTC, mkilpatrick commented on src/utils/themeResolver.ts
> +export const themeResolver = <T extends PlainObject>(
Add tests for these different functions

2024-10-02 17:49 UTC, mkilpatrick commented
> add docs to READ.me for this too!

Idk if we need a README if it's internal

2024-10-02 17:51 UTC, asanehisa commented
> > add docs to READ.me for this too!
> 
> Idk if we need a README if it's internal

Oh if its internal, it should be in src/internal/utils?

2024-10-03 16:05 UTC, mkilpatrick commented on src/utils/themeResolver.ts
> +  console.log("marketerTailwindConfig", marketerTailwindConfig);
rm logs

2024-10-03 17:33 UTC, briantstephan commented on src/utils/themeResolver.ts
> +  console.log("marketerTailwindConfig", marketerTailwindConfig);
Oops, done

2024-10-03 17:37 UTC, benlife5 approved these changes

2024-10-03 18:49 UTC, jwartofsky-yext requested changes
lgtm other than nitpicks

2024-10-03 18:49 UTC, jwartofsky-yext commented on src/utils/themeResolver.test.ts
> +const developerTailwindConfig: TailwindConfig = {
same

2024-10-03 18:49 UTC, jwartofsky-yext commented on src/utils/themeResolver.test.ts
> +const marketerTailwindConfig: TailwindConfig = {
same

2024-10-03 18:49 UTC, jwartofsky-yext commented on src/utils/themeResolver.test.ts
> +const themeConfig: ThemeConfig = {
put this above the tests

2024-10-03 19:25 UTC, jwartofsky-yext approved these changes
lgtm

2024-10-03 19:48 UTC, mkilpatrick approved these changes

2024-10-03 19:54 UTC, briantstephan commented on src/utils/themeResolver.test.ts
> +const marketerTailwindConfig: TailwindConfig = {
Ack

2024-10-03 19:54 UTC, briantstephan commented on src/utils/themeResolver.test.ts
> +const developerTailwindConfig: TailwindConfig = {
Ack

2024-10-03 19:55 UTC, merged